name: dcdp_mycode2_phase_retrieval

conditioning:
  method: ps
  params:
    scale: 1

measurement:
  operator:
    name: phase_retrieval
    oversample: 2.0
    resolution: 256
    input_range: zero_one

  noise:
    name: gaussian
    sigma: 0.05
